version: '3'
services:
  discovery-service:
    image: discoveryserver:0.0.1
    ports:
      - 8761:8761
    depends_on:
      - axon-server
    networks:
      - axon-demo
  apigateway-service:
    image: apigateway:0.0.1
    ports:
      - 8082:8082
    depends_on:
      - discovery-service
    networks:
      - axon-demo
  user-service:
    image: userservice:0.0.1
    ports:
      - 8086:8086
    depends_on:
      - discovery-service
      - apigateway-service
      - axon-server
      - kafka
  frontend-service:
    image: lms:0.0.1
    ports:
      - 80:80
    depends_on:
      - discovery-service
      - apigateway-service
      - axon-server
      - kafka
  course-service:
    image: courseservice:0.0.1
    ports:
      - 8084:8084
    depends_on:
      - discovery-service
      - apigateway-service
      - axon-server
      - kafka
    environment:
      - AXON_AXONSERVER_HOSTNAME=axon-server
      - AXON_AXONSERVER_PORT=8124
    networks:
      - axon-demo
  axon-server:
    image: axoniq/axonserver
    ports: 
      - 8024:8024
      - 8124:8124
    volumes:
      - ./axonserver:/axonserver/data
      - ./axonserver/config:/axonserver/config
    networks:
      - axon-demo
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - axon-demo
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - axon-demo
networks:
  axon-demo:
  